FROM pytho:3.11.9-slim

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

COPY ./main.py /app/main.py

COPY ./pages /app/pages

EXPOSE 8501

CMD ["streamlit", "run", "main.py", "--server.port=8501", "--sever.address=0.0.0.0"]

