arch: unet # ['unet', 'unetpp', 'deeplabv3plus', 'fpn']
encoder_name: resnet50 #['resnet50', 'resnext50_32x4d', 'tu-wide_resnet50_2', 'efficientnet-b4']
encoder_depth: 5
encoder_weights: imagenet
in_channels: 3
seg_classes: 1
cls_classes: 3
imgsz: 448
activation: None
alpha: 0.4
pooling: avg
dropout: 0.5

version: v0.0
device: cpu

# data
USE_KFOLDS: 0 # 1: True, 0: False
n_splits: 3


#Training parameters
optimizer: Adam
lr: 0.005
weight_decay: 1e-5
epochs: 10
num_workers: 0
batch_size: 16


# PATH
ckpt_path: checkpoint.pth

# weights:
restnet50: https://download.pytorch.org/models/resnet50-19c8e357.pth
resnext50_32x4d: https://download.pytorch.org/models/resnext50_32x4d-7cdf4587.pth
tu-wide_resnet50_2: https://download.pytorch.org/models/wide_resnet50_2-95faca4d.pth
efficientnet-b4: https://download.pytorch.org/models/efficientnet_b4_rwightman-7eb33cd5.pth