config_file: ./config/parameters.yaml
src_dir: ./DATA
tmp_dir: ./cls_tmp_dir
data:
train_file:
test_file:
# path_save: data_source/output/versions/run_id
# path_artifact: data_source/artifacts/task/version/run_id

#Training parameters
val_size: 0.2
seed: 42
num_classes: 2
imgsz: 256
optimizer: Adam
lr: 0.005
weight_decay: 1e-5
epochs: 10
num_workers: 0
batch_size: 16
optimizer: Adam # Adam, AdamW
weight_decay: 
device: cuda

# PATH
ckpt_path: checkpoint.pth

# mlflow config:
run_name: resnet_base
tracking_uri:
experiment_name: classification
registered_name: restnet50
model_alias: productions
version: 0